### PR TITLE
Add on_overwrite source config

### PR DESCRIPTION
**Pull request by matt-royal**
When set, the out binary will first check to see that no file exists at
the remote path. It will fail if there is already a file present.

### CODE REVIEW

**Comment by matt-royal** [comment]
Here's the scenario I made this change to address:

- The s3 resource is configured with a regexp that captures the version
- The job that puts to the resource runs once (correctly)
- Due to a flaw in our pipeline, the job is triggered again with a different input but the same version
- The second run puts to the resource, overwriting the original file on s3. However, because the version ID hasn't changed, Concourse keeps its cached copy of the resource (which is now wrong/stale)

In our case, the correct behavior is to cause the second put to fail. There are likely cases where the correct solution would be to allow the put to succeed, but change the version JSON so that Concourse sees it as a new resource.

**Comment by matt-royal** [comment]
As the new commit states, we've realized that we need the put to succeed for our specific use case. To accommodate this I changed the config to `on_overwrite`, which has 3 possible configurations. The new option ("ignore") does what we need: the put succeeds, but no changes are made in s3.

 In implementing "ignore", I couldn't find a reasonable way to get the VersionID of the existing file in S3. Due to this, I decided to disallow the "ignore" setting when using "versioned_file", since this indicates that the bucket is versioned (and VersionID is needed). If you have a better idea for solving this problem, I'm open to making further changes

**Comment by matt-royal** [comment]
@rizwanreza I was surprised to see that we were using `versioned_file`, since our release tarballs always have a version in their name. I was able to change our pipeline so that we use `regexp` instead, and that regexp matches only the exactly correct version. That worked with the code in this PR so I think we can write that off as a blocker for us.

**Comment by cirocosta** [comment]
During acceptance, it got me wondering if using `on_overwrite` with `versioned_file` should fail in any case instead of only `ignore` :thinking: 

thinking about the semantics of having versioning enabled for a bucket, it feels weird to have the inability to overwrite at all. And, as you mentioned, having versioning enabled you'd have a different version being produced for every run of a `put`, even if the contents of the files don't change, thus, not having a cached volume for that resource version (as it'd be new) :thinking: 

wdyt of making it fail in any scenario where `on_overwrite` is specified together with `versioned_file`? do you think that makes sense? (this was my first time using versioned files in S3, so I might be seeing this kinda wrong :sweat_smile:)

thanks!

**Comment by xtremerui** [comment]
@matt-royal hi, are you still interested in this PR? thx

**Comment by matt-royal** [comment]
I don't believe my old team needs this functionality anymore. I'll go ahead and close it since there were concerns with the original implementation

**Pull request closed without merging**
