### PR TITLE
Add chained credentials

### PR DESCRIPTION
**Pull request by ghostsquad**
## Description

* Allows EC2Role creds for Concourse running in AWS

_Note:_ It looks like `go fmt` modified a few extra lines.

## Test Output

```
Ran 0 of 29 Specs in 0.012 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 29 Skipped PASS
Running Suite: Out Suite
========================
Random Seed: 1522091803
Will run 20 of 20 specs

••••••••••••••••••••
Ran 20 of 20 Specs in 0.015 seconds
SUCCESS! -- 20 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
Running Suite: Versions Suite
=============================
Random Seed: 1522091803
Will run 22 of 22 specs

••••••••••••••••••••••
Ran 22 of 22 Specs in 0.007 seconds
SUCCESS! -- 22 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
Removing intermediate container 462b74b81892
 ---> 2e399e4a2b5e
Step 25/25 : FROM resource
 ---> e6120f6a912d
Successfully built e6120f6a912d
Successfully tagged concourse/s3-resource:test
```

Let me see if I can get a test bucket going that I can try out.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@ghostsquad Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/s3-resource&pullRequestId=96)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/s3-resource&pullRequestId=96) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@ghostsquad Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/s3-resource&pullRequestId=96)!

**Comment by vito** [comment]
Hey, checking in on this a bit late, sorry. Is this good to go? You mentioned performing some additional testing.

Looks due for a rebase since I took so long to check in. We should maybe set up some automated tests for this too so that it doesn't regress, though that may take a lot of effort since we'd need a worker configured with special access to a test bucket...

Side note: in the past we've turned down changes like this, as configuring authentication on the workers and having each resource support multiple ways to configure credentials hits on a couple anti-patterns ([`contributor-burden`](https://github.com/concourse/concourse/wiki/Anti-Patterns#contributor-burden) and [`worker-state`](https://github.com/concourse/concourse/wiki/Anti-Patterns#worker-state)). The PRs for supporting this just keep coming though and it's starting to feel like a losing puritanical battle, so I'm not 100% against merging this, but I'm still gonna stamp the labels on it. :)

**Comment by ghostsquad** [comment]
@vito I've fixed the merge conflict. This has also been manually tested thoroughly (read production deployed) on our end, and seems to do the job.

**Comment by vito** [comment]
I had to revert this. (It also never made it in to a release, so I've removed the milestone.)

This seems to break anonymous credential use. I left details in the revert commit: https://github.com/concourse/s3-resource/commit/4a519d8b695270cb03718398ca00230b47f5fc45

**Pull request merged**
