### PR TITLE
adding debug flag to allow troubleshooting resource

### PR DESCRIPTION
**Pull request by calebwashburn**
Debug option dumps information into standard err

### CODE REVIEW

**Comment by sneal** [comment]
This sure would have been handy today while trying to debug this resource with a storage appliance with an "S3 compatible" API.

**Comment by aegershman** [comment]
If you don't mind me asking @vito could you elaborate on your apprehension to having `debug` log levels within the resource? Some thoughts:

- Seems analogous to configuring log-levels within a regular webapp.
- I could see this being beneficial to both resource developers and resource consumers ([as per the comment above](https://github.com/concourse/s3-resource/pull/113#issuecomment-453253852)). 
- I could see this being beneficial for resource developers who are trying to get logs from consumers who are having problems; e.g., akin to asking for a stacktrace.
- Doing debugging via turning up log-levels through a param feels easier than forking the resource source, modifying it, then building + pushing, and testing it.

Is the concern with having `debug` be a _param_ of the resource? Or having the debug logs at all?

**Comment by vito** [comment]
@aegershman Making debug logging configurable is reasonable, my main concern was with the pattern that may follow, which is PRs for adding specific log lines to specific places in order to debug a specific problem the user is seeing. In this situation it seems like a faster feedback loop would be to just run your own custom type with those log lines added, rather than PRing them upstream and waiting for a merge + new release.

If those log lines are there ahead of time then it's obviously quicker to just be able to set a `debug: true`, but at least in this case it looks like they weren't, e.g.:

https://github.com/concourse/s3-resource/pull/113/files#diff-d0b230e2e7438d58177fda7f067fc05bR211

Using the bool to enable debug logging in the AWS client makes sense at least, I'm mostly worried about ad-hoc logging being added at the same time.

There's also risk of dumping credentials to build logs, which users may not expect from a simple `debug: true`:

https://github.com/concourse/s3-resource/pull/113/files#diff-fefaf1afc0068e7a0b2e01b2b75fbfc9R71

**Comment by vito** [comment]
Closing per my [previous comment](https://github.com/concourse/s3-resource/pull/113#issuecomment-454846969). (Also looks like the git history got a little borked anyway.)

Thanks!

**Pull request closed without merging**
