### PR TITLE
improve permission / resource explanation in README

### PR DESCRIPTION
**Pull request by dhrapson**
Hi, we thought the AWS permissioning section of  your README could do with a little extra detail so we added. Hope thats OK.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dhrapson Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/s3-resource&pullRequestId=67)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/s3-resource&pullRequestId=67) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dhrapson Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/s3-resource&pullRequestId=67)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/s3-resource&pullRequestId=67) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by chendrix** [comment]
@dhrapson if you'd please sign the CLA. we can get this merged.

**Comment by pivotal-issuemaster** [comment]
@dhrapson Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/s3-resource&pullRequestId=67)!

**Pull request merged**
