### PR TITLE
Optionally download tags when getting object

### PR DESCRIPTION
**Pull request by mdelillo**
This adds a new param to `in` requests called `download_tags`. It will write the [S3 object tags](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html) as key:value pairs to `tags.json`. It is disabled by default.

The `SetTags` function on `s3client` is currently only used for testing, but it could be used to allow tags to be written in `out` (#119).

### CODE REVIEW

**Comment by xtremerui** [comment]
Hi @mdelillo , it seems there is test failure on both alpine and ubuntu build.

```
• Failure in Spec Setup (BeforeEach) [0.573 seconds]
in
/go/src/github.com/concourse/s3-resource/integration/in_test.go:21
  when download_tags is true
  /go/src/github.com/concourse/s3-resource/integration/in_test.go:442
    writes the tags to tags.json [BeforeEach]
    /go/src/github.com/concourse/s3-resource/integration/in_test.go:494

    Expected error:
        <s3.requestFailure>: {
            RequestFailure: {
                awsError: {
                    code: "AccessDenied",
                    message: "Access Denied",
                    errs: nil,
                },
                statusCode: 403,
                requestID: "8C772CDF23216B9B",
            },
            hostID: "ftWDFFDn+uvPyhLC4DjQTX2DmU0ErgjfA5MpKqPduWwx+YYjUrUlOINGcHd7UdYtGfyLr7rl9ik=",
        }
        AccessDenied: Access Denied
        	status code: 403, request id: 8C772CDF23216B9B, host id: ftWDFFDn+uvPyhLC4DjQTX2DmU0ErgjfA5MpKqPduWwx+YYjUrUlOINGcHd7UdYtGfyLr7rl9ik=
    not to have occurred

    /go/src/github.com/concourse/s3-resource/integration/in_test.go:486
```

**Comment by mdelillo** [comment]
From the error it seems like the S3 token doesn't have permission to write object tags. I actually ended up solving my original problem in a different way, so if this isn't easily mergeable then I'll probably close it out.

**Comment by xtremerui** [comment]
I have config the IAM to have right permissions for the tests it looks good now. Will try to move this PR forward.

**Comment by xtremerui** [comment]
@mdelillo all looks good. The only concern is the IAM change that needed for using `download_tags`. Could you update the readme either at https://github.com/concourse/s3-resource/blob/7b1ba3b876112353df0f78eef8b67ea7e3912fb4/README.md#required-iam-permissions or where you added `download_tags` to make the usecase clear? Thx!

**Comment by mdelillo** [comment]
That makes sense, I added it to Required IAM Permissions. I also added a section in the integration tests since the `s3:PutObjectTagging` is only needed during testing.

**Pull request merged**
