### PR TITLE
Allow non_anonymous S3 access without specified keypair (i.e. instance profile)

### LINKED ISSUE #65: Use the default credentials for the aws client
By default, the aws client will use a credential provider chain to discover authentication. If a user doesn't specify an access key id and secret access key then the defaults should be left alone. Currently the defaults are set to credentials.AnonymousCredentials

https://github.com/concourse/s3-resource/blob/master/s3client.go#L87

Details on the provider chain: https://github.com/aws/aws-sdk-go/blob/b2dc98bb584e48b0f5f39c93110633173c5da43c/aws/config.go#L38

This would mean that if the worker is an EC2 instance, then the IAM Profile associated with the instance could be used.

### PR DESCRIPTION
**Pull request by troyready**
This is @robbruce's commit to fix #65 ; I've built it and confirmed that it works as expected.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@troyready Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/s3-resource&pullRequestId=69)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/s3-resource&pullRequestId=69) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@troyready Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/s3-resource&pullRequestId=69)!

**Comment by willejs** [comment]
👍 I was just about to make this PR!
It makes sense to use IAM roles when using AWS resources, and not implementing vault as per #291. @vito thoughts? Merge? :)

**Comment by robbruce** [comment]
> @willejs It makes sense to use IAM roles when using AWS resources, and not implementing vault as per #291. @vito thoughts? Merge? :)

Personally I think that any access to an AWS resource should be controllable, so if concourse is running on AWS, then allow the IAM Profile with that EC2 or IAM Role for the ECS task to define the access as well as being able to provide access keys.

**Comment by willejs** [comment]
@robbruce i agree, but many workers can run on an instance and under and ECS task, and could get access to the role. However, i think its up to you to control the permissions you give it.
Ive started an issue here, to cover all resources.
https://github.com/concourse/concourse/issues/976

**Comment by derBroBro** [comment]
@troyready thank you very much for the PR! 😄 
Are there any plans when the PR will be merged?

**Comment by mariash** [comment]
I put a comment on this issue why this issue is an anti-pattern.

https://github.com/concourse/concourse/issues/976#issuecomment-309150218

We are planning to investigate Vault integration as a solution to this problem.

**Comment by jtarchie** [comment]
We are considering this pull request dead due to inactivity. Please feel free to reopen a new pull request with the requested changes. Thanks!

**Pull request closed without merging**
