### PR TITLE
add v2 signature signing, retry in case of multipartupload failures

### PR DESCRIPTION
**Pull request by JamesClonk**
adds v2 signature signing for S3 compatible provides that do not support v4.
also does retries in case of multipartupload failures, as the s3manager does not handle that by himself.

### CODE REVIEW

**Comment by cjcjameson** [comment]
I'm (possibly) eager to support getting the v2 support in; is it possible to separate this PR into two parts for the retry logic, if that makes it easier to get merged in?

**Comment by vito** [comment]
Yeah I'm also not a huge fan of tying the retry logic into this. Is that related to v2 signing at all?

**Comment by JamesClonk** [comment]
The retry logic is not related directly to v2 signing, but I added it as it's essential for us in order to be able to use the s3-resource with v2 signatures.
Our S3 compatible provider sometimes has problems with MultiPartUpload, and as per AWS docs suggestion for the s3manager we added a retry for these specific error cases.
We also had to do that on the s3cli that BOSH itself uses, otherwise we're seeing lots of failed uploads.
https://github.com/pivotal-golang/s3cli/blob/master/client/client.go#L78

**Comment by ljfranklin** [comment]
@JamesClonk @vito looks like the aws-sdk recently added retries for multi-part downloads, not sure about uploads: https://github.com/aws/aws-sdk-go/issues/466

**Comment by vito** [comment]
@JamesClonk I think we should separate out the upload retry logic. It may even be broken at the moment; the upload input is constructed with a single `Body`, and if an upload gets partway through and then fails, the next attempt will only upload the bits that were remaining.

**Comment by JamesClonk** [comment]
@vito OK, I removed the retry logic. It's just the v2 signing now.

Since these multipartupload failures happened rather sporadic and in a non-reproducible way before the pivotal-golang/s3cli was patched, I'll just have to wait and see now if they'll still occur on our S3 provider or not. I might come back again at a later time regarding that topic :sweat_smile:

**Comment by vito** [comment]
Looks good, thanks!

**Pull request merged**
